version: 2
updates:
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    # Raise pull requests against a specific branch
    target-branch: "main"
    # Allow up to 100 open pull requests for npm dependencies
    open-pull-requests-limit: 100
    # Specify labels for npm pull requests
    labels:
      - "npm"
      - "dependencies"
    # Prefix all commit messages with "npm"
    # include a list of updated dependencies
    commit-message:
      prefix: "npm"
      include: "scope"
